apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: webapp-cpu-scaler
spec:
  scaleTargetRef:
    name: webapp
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 30 # KEDA side, seconds
  pollingInterval: 5 # seconds
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "60" # taget CPU %
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 60   # HPA side (was 300)
          selectPolicy: Min
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15              # allow fast downscale
          - type: Pods
            value: 10
            periodSeconds: 15
        scaleUp:
          stabilizationWindowSeconds: 0
          selectPolicy: Max
          policies:
            - type: Percent
              value: 200
              periodSeconds: 15
            - type: Pods
              value: 10
              periodSeconds: 15
